name: CI/CD

on:
  push:
  pull_request:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build ⚒️
    uses: ./.github/workflows/build.yml

  test:
    name: Test 🧪
    needs: [build]
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/test.yml

  deploy:
    name: Deploy 🚀
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml

  # release:
  #   permissions:
  #     contents: write
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: [build, test]
  #   name: Release 🚢
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/download-artifact@v3
  #     with:
  #       name: dist
  #       path: ${{ env.dist }}
  #   - uses: softprops/action-gh-release@v1
  #     with:
  #       files: ${{ env.dist }}

