name: CI/CD

on:
  push:
  pull_request:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  build:
    name: Build ⚒️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/node.js.yml
      - run: npm run build -- --base-href /${{ github.event.repository.name }}/
      - run: npm test -- --browsers=Headless --no-watch
      - run: cp ${{ env.dist }}/index.html ${{ env.dist }}/404.html
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}

  test:
    needs: [build]
    name: Test 🧪
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}
      - run: npm test -- --browsers=Headless --no-watch

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build, test]
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Deploy 🚀
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}
      - uses: actions/configure-pages@v1
        if: github.ref == 'refs/heads/main'
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.dist }}
      - uses: actions/deploy-pages@v1
        id: deployment
        if: github.ref == 'refs/heads/main'

  release:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, test]
    name: Release 🚢
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: ${{ env.dist }}
    - uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.dist }}

