name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install ⬇️
        run: npm ci

      - name: Build 🔧
        run: npm run build -- --base-href /angular-codespace/

      - name: Test 🧪
        run: npm run test:ci

      - name: Fallback to index.html 🔁
        run: cp dist/${{ github.event.repository.name }}/index.html dist/${{ github.event.repository.name }}/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist/${{ github.event.repository.name }}
