name: Build and Deploy

on:
  push:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    name: Build and Deploy ⚒️🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build -- --base-href /${{ github.event.repository.name }}/
      - run: npm test -- --browsers=Headless --no-watch
      - run: cp ${{ env.dist }}/index.html ${{ env.dist }}/404.html
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/main'
    needs: build-and-deploy
    name: Deploy 🚀
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}
      - uses: actions/configure-pages@v1
        if: github.ref == 'refs/heads/main'
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.dist }}
      - uses: actions/deploy-pages@v1
        id: deployment
        if: github.ref == 'refs/heads/main'

  release:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-and-deploy
    name: Release 🚢
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: ${{ env.dist }}
    - uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.dist }}

