name: Build and Deploy ⚒️🚀

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    name: Build and Deploy ⚒️🚀
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install ⬇️
        run: npm ci

      - name: Build 🔧
        run: npm run build -- --base-href /${{ github.event.repository.name }}/

      - name: Test 🧪
        run: npm test -- --browsers=Headless --no-watch

      - name: Fallback to index.html 🔁
        run: cp ${{ env.dist }}/index.html ${{ env.dist }}/404.html

      - name: Setup Pages 📃
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v1

      - name: Upload artifact ⬆️
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.dist }}

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v1
