name: Build and Deploy ⚒️🚀

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install ⬇️
        run: npm ci

      - name: Build 🔧
        run: npm run build -- --base-href /angular-codespace/

      - name: Test 🧪
        run: npm run test:ci

      - name: Fallback to index.html 🔁
        run: cp dist/${{ github.event.repository.name }}/index.html dist/${{ github.event.repository.name }}/404.html

      - name: Setup Pages 📃
        if: github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v1
        
      - name: Upload artifact ⬆️
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/'
          
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v1
