name: Deploy 🚀

on:
  workflow_call:

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}
      - uses: actions/configure-pages@v1
        if: github.ref == 'refs/heads/main'
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.dist }}
      - uses: actions/deploy-pages@v1
        id: deployment
        if: github.ref == 'refs/heads/main'
