name: Test

on:
  workflow_call:

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - uses: actions/cache@v3
        id: cache-nodemodules
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}
      - run: npm test -- --browsers=Headless --no-watch
