name: Test

on:
  workflow_call:

env:
  dist: dist/${{ github.event.repository.name }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/checkout-install
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ${{ env.dist }}
      - run: npm test -- --browsers=Headless --no-watch
